Number Input MVP
naked-ui/vue pull request #102
Opened 2021-06-18 09:29 UTC by ibockowsky

2021-06-18 15:27 UTC, allozaur commented
- [ ] `nativeControls`
- [ ] Optional width auto-adjustion based on digits amount (`adjustWidth`)
- [ ] Data binding has to work also with native spinner + changing values from keyboard
- [ ] Holding `plus` / `minus` should start spinning the value

2021-06-18 15:28 UTC, allozaur requested changes
- [x] `nativeControls`
- [ ] Optional width auto-adjustion based on digits amount (`adjustWidth`)
- [ ] Data binding has to work also with native spinner + changing values from keyboard
- [ ] Holding `plus` / `minus` should start spinning the value

2021-06-21 16:21 UTC, ibockowsky commented
In my opinion, implementing auto-adjusting is overkill for now and it may be over-opinioned by us.

2021-06-23 12:44 UTC, allozaur approved these changes

2021-06-23 12:57 UTC, merged