REFACTOR: extended html validation
naked-ui/vue pull request #50
Opened 2021-03-29 11:19 UTC by Razz21

validation flow (for simple text input):

base html5 validation:
- `checkValidity()` is triggered on every keyup (current event)
- on `invalid` input event (triggered by html's `checkValidity()` or `submit` method) custom `setValidity` method is called that populate validation messages (custom, if provided in `customMessages` object prop or pre-defined), 
- validation stops

custom rules:
- if base html5 validation passed, custom `rules` array is checked
example rule function:
```
(val) => !!val || "This field is required!"
```
- populate `validationMessages` with custom rules errors

TODO: 
- [ ] custom validation events trigger (e.g. `blur`,'input`)

2021-03-30 16:20 UTC, allozaur requested changes

2021-03-30 16:20 UTC, allozaur commented on .storybook/main.js
>    }
```suggestion
  }
  
```

2021-03-30 16:20 UTC, allozaur commented on src/components/nCheckboxInput/nCheckboxGroup.scss
> +    &[disabled="disabled"],
@Razz21 we want to avoid changing elements' opacity from within the library unless it's native browser's behavior (as it happens with `<input>` and `<textarea>` tags when they have `disabled` attribute). Please remove this CSS rule

2021-03-30 16:20 UTC, allozaur commented on src/components/nCheckboxInput/nCheckboxInput.scss
> +  }
```suggestion
  } 
  
```

2021-03-30 16:20 UTC, allozaur commented on src/components/nRadioInput/nRadioGroup.scss
> +    &[disabled="disabled"],
@Razz21 we want to avoid changing elements' opacity from within the library unless it's native browser's behavior (as it happens with `<input>` and `<textarea>` tags when they have `disabled` attribute). Please remove this CSS rule

2021-03-30 16:20 UTC, allozaur commented on src/components/nRadioInput/nRadioInput.scss
> +  }
```suggestion
  } 
  
```

2021-03-30 16:20 UTC, allozaur commented on src/components/nRadioInput/nRadioInput.stories.js
> +    spacing: {
@Razz21 rename `spacing` prop to `gap` to follow the naming pattern defined earlier with other components

2021-03-30 16:21 UTC, Razz21 commented on src/components/nRadioInput/nRadioInput.stories.js
> +    spacing: {
@allozaur was made by purpose: to not override original `gap` in inputs

2021-03-30 16:29 UTC, Razz21 commented on src/components/nCheckboxInput/nCheckboxGroup.scss
> +    &[disabled="disabled"],
@allozaur yeah, thoughtlessly copied

2021-03-30 16:29 UTC, Razz21 commented on src/components/nRadioInput/nRadioGroup.scss
> +    &[disabled="disabled"],
thoughtlessly copied

2021-04-07 11:00 UTC, allozaur approved these changes

2021-04-07 11:00 UTC, allozaur commented on src/components/nCheckboxInput/nCheckboxGroup.vue
> +      type: [String, String],
```suggestion
      type: [Number, String],
```

2021-04-07 11:00 UTC, allozaur commented on src/components/nCheckboxInput/nCheckboxInput.scss
> +}
```suggestion
}

```

2021-04-07 11:05 UTC, merged