FEAT: custom color for customMessages
naked-ui/vue pull request #54
Opened 2021-04-11 13:49 UTC by Razz21

validation `customMessages` supports nested objects with `text` / `color` keys

this should work
```js
customMessages: { valueMissing: 'Value is required!'}, // colorInvalid as fallback

customMessages: { valueMissing: { // colorInvalid as fallback
    text: 'Value is required!', 
  } },

customMessages: { valueMissing: { // uses custom color
    text: 'Value is required!',
    color: 'green'
  } },
```

2021-04-11 22:04 UTC, allozaur commented on src/components/nCheckboxInput/nCheckboxInput.stories.js
> +    color: 'green'
```suggestion
    color: 'pink'
```

2021-04-12 16:29 UTC, allozaur requested changes
@Razz21 we still have some imperfections.

1. When there is no value in `pattern` prop we still are getting `patternMismatch` error.

![Zrzut ekranu 2021-04-12 o 18 26 12](https://user-images.githubusercontent.com/37627284/114428842-fc100f80-9bbc-11eb-83f3-b38bf8ee4a30.jpg)

2. Overriding `typeMismatch` or `patternMismatch` doesn't seem to function properly.

![Zrzut ekranu 2021-04-12 o 18 24 22](https://user-images.githubusercontent.com/37627284/114428862-0205f080-9bbd-11eb-8f08-86d62d20f982.jpg)

2021-04-12 17:57 UTC, Razz21 commented
@allozaur 
1. `nEmailInput` already uses hardcoded `pattern` attribute
![obraz](https://user-images.githubusercontent.com/32792205/114439082-dee13e00-9bc8-11eb-8c6f-95c738d3ec46.png)
2. second option is to remove `email` type and rely only on regex `pattern` to bypass typeMismatch error
from [MDN](https://developer.mozilla.org/en-US/docs/Web/API/ValidityState/typeMismatch):
```
ValidityState.typeMismatch
The read-only typeMismatch property of a ValidityState object indicates if the value of an <input>, 
after having been edited by the user, does not conform to the constraints set by the element's type attribute.
```

2021-04-13 20:00 UTC, allozaur commented
Still couple improvements are needed:

1. Custom `rules` prop doesn't work for:

- Date Input
- Email Input
- Url Input

2. Validation outline colors don't work for

- Checkbox Input
- Date Input
- Radio Input

2021-04-14 08:10 UTC, Razz21 commented
1. maybe because of this code
```js
const htmlValid = target.checkValidity() // triggers `invalid` input event

// base validation passed
if (htmlValid) {
// check custom validation rules
 this.validateCustomRules(target)
}
```
triggers custom rules **only when** native rules passed

2021-04-22 12:13 UTC, allozaur approved these changes

2021-04-22 12:31 UTC, allozaur commented
Alright, so validation logic supporting browser-native validation seems to be working fine. The one exception is Range Input as it potentially utilising more than one `<input type="range">` iniside. This feature will be handled through #66

2021-04-22 12:31 UTC, merged