Table MVP
naked-ui/vue pull request #88
Opened 2021-06-13 14:04 UTC by allozaur

2021-06-14 11:34 UTC, ibockowsky commented
- [ ] There're currently two names of the same style variable `--columns` and `--columns-amount` , choose one and refactor code
- [ ] Implement tbody scroll feature

2021-06-14 13:11 UTC, ibockowsky requested changes
- [x] There're currently two names of the same style variable `--columns` and `--columns-amount` , choose one and refactor code
- [ ] Implement tbody scroll feature

2021-06-14 15:07 UTC, allozaur commented
@ibockowsky i have implemented the requested points

2021-06-15 07:13 UTC, ibockowsky approved these changes

2021-06-15 08:45 UTC, merged